define gg = Character("Я")
define whisper = Character("Шепіт")
define cashier = Character("Касирка")
define denis = Character("Денис")
define bogdan = Character("Богдан")
define vasyl = Character("Дядько Василь")
define natalia = Character("Наталя")
define liza = Character("Ліза")
